### ISSUE TITLE
Can you share the realsense mount drawing for RG2 gripper?

### ISSUE THREAD

**Issue by haotruongnhat** [matchRos/MuR_Vision#1]
Hi author, I have a robot that has the same configuration as you did, but I don't know how to mount the Realsense camera properly on RG2. Could you please share the CAD, SOLIDWORK drawing file? I'm really appreciated.

**Comment by TobiasRecker** [comment]
Hi, I added a folder called "Realsense_CAD". It includes a SOLIDWORKS model file and an STL.
The mount is attached to the two screw holes at the front of the gripper.
